version: "2"

services:
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./docker/db:/tmp/mysql
      - db_files:/var/lib/mysql/
    command: mysqld --init-file="/tmp/mysql/schema.sql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ''
    ports:
      - "9001:80"
    links:
      - db
    depends_on:
      - db

  php:
    build: ./docker/php

    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./wordpress:/var/www/html:rw
    links:
      - db
    depends_on:
      - db

  web:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./wordpress:/var/www/html:rw
    ports:
      - "9999:80"
    links:
      - php
    depends_on:
      - php

volumes:
  db_files:
