gulp        = require 'gulp'
browserSync = require 'browser-sync'
reload      = browserSync.reload
sass        = require 'gulp-sass'
sass        = require 'gulp-coffee'

if 'WORDPRESS_THEME' in process.env
  theme_folder = './wp-content/themes/' + process.env.WORDPRESS_THEME
else
  theme_folder = './wp-content/themes/twentysixteen'

# browser-sync task for starting the server.
gulp.task 'browser-sync', ->
  #watch files
  files = [
    theme_folder+'/**/*.css'
    theme_folder+'/**/*.js'
    theme_folder+'/**/*.php'
  ]
  #initialize browsersync
  browserSync.init files,
    proxy: 'php:9998'
    notify: false

gulp.task 'sass', ->
  gulp.src(['sass/*.sass', 'sass/*.scss'])
      .pipe(
          sass())
      .pipe(
          gulp.dest(theme_folder))
      .pipe(
          reload(stream: true))

gulp.task 'coffee', ->
  gulp.src('coffee/*.coffee')
      .pipe(
          coffee())
      .pipe(
          gulp.dest(theme_folder + '/js'))
      .pipe(
          reload())


gulp.task 'serve', [
  'sass'
  'coffee'
  'browser-sync'
], ->
  gulp.watch ['sass/**/*.sass', 'sass/**/*.scss'], [ 'sass' ]
  gulp.watch 'coffee/**/*.coffee', [ 'coffee' ]

# ---
# generated by js2coffee 2.1.0
