themePath: 'wordpress/wp-content/themes/twentysixteen'
browsersync:
  port: 3000
  open: "external"
  notify: true
  proxy:
    target: '0.0.0.0:9999'
    ws: true
  ui:
    port: 3001
    weinre:
      port: 3030
  ghostMode:
    clicks: true
    forms: true
    scroll: true
